- name: Gather facts about all the interested EC2 instances
  ec2_instance_facts:
    filters:
      "tag:Name": "{{ec2_tag_name}}"
      "instance-state-name": "running"
  register: ec2_all

- name: Ensure the ELB Target Group is present
  elb_target_group:
    name: "{{ elb_target_group }}"
    protocol: HTTP
    port: 80
    vpc_id: "{{ elb_target_vpc }}"
    state: present
    targets:
      - Id: "{{ item.instance_id }}"
        Port: 80
  with_items: "{{ ec2_all.instances }}"

- name: Ensure the presence of the load balancer
  elb_application_lb:
    name: "{{ elb_name }}"
    state: present
    region: "{{ ec2_region }}"
    security_groups:
      - "{{ ec2_security_group }}"
    subnets:
      - "{{ ec2_subnet_id }}"
      - "{{ elb_extra_subnet_id }}"
    listeners:
      - Protocol: HTTP
        Port: 80
        DefaultActions:
          - Type: forward # Required. Only 'forward' is accepted at this time
            TargetGroupName: "{{ elb_target_group }}" # Required. The name of the target group
