---
- name: Provision a number of EC2 instances
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    ansible_ssh_user: ec2-user
    ansible_ssh_private_key_file: ~/.ssh/keyone.pem

  roles:
    - ec2_instances
