---
- name: Check for username
  become: yes
  user:
    name: "{{ dev_username }}"
    comment: "{{ dev_fullname }}"
    password: pass1234
    group: admin
    update_password: on_create
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
    state: present
    shell: /bin/bash
    createhome: yes
    home: "/Users/{{ dev_username }}"
