dockitems_to_remove:
  - Launchpad
  - Mail
  - Safari
  - Contacts
  - Notes
  - Reminders
  - Maps
  - Photos
  - Messages
  - FaceTime
  - iTunes
  - iBooks
  - App Store
  - System Preferences
  - Calendar
  - Siri
  - Downloads

dockitems_to_persist:
  - name: Google Chrome
    path: "/Applications/Google Chrome.app"
    pos: 1
  - name: Firefox
    path: "/Applications/Firefox.app"
    pos: 2
  - name: WebStorm
    path: /Applications/WebStorm.app
    pos: 3
  - name: Slack
    path: /Applications/Slack.app
    pos: 4
  - name: Terminal
    path: /Applications/Utilities/Terminal.app
    pos: 5
  - name: Sourcetree
    path: /Applications/Sourcetree.app
    pos: 6
