---
- name: Ensure that the instances are running
  ec2:
    key_name: "{{ ec2_keypair }}"
    instance_type: "{{ ec2_instance_type }}"
    image: "{{ ec2_image }}"
    region: "{{ ec2_region }}"
    wait: yes
    group_id: "{{ ec2_security_group }}"
    instance_tags:
      Name: "{{ec2_tag_Name}}"
      foo: bar
    exact_count: 3
    count_tag: foo
    vpc_subnet_id: "{{ ec2_subnet_id }}"
    assign_public_ip: yes
    volumes:
      - device_name: /dev/xvda
        volume_type: gp2
        volume_size: "{{ ec2_volume_size }}"
        delete_on_termination: true
  register: ec2

- name: Add new instance to host group
  add_host:
    hostname: "{{ item.public_ip }}"
    groupname: launched
  with_items: "{{ ec2.instances }}"

- name: Wait for SSH to come up
  delegate_to: "{{ item.public_dns_name }}"
  wait_for_connection:
    delay: 60
    timeout: 320
  with_items: "{{ ec2.instances }}"
