---
- name: Ensure that the instances are running
  ec2:
    key_name: "{{ ec2_keypair }}"
    instance_type: "{{ ec2_instance_type }}"
    image: "{{ ec2_image }}"
    region: "{{ ec2_region }}"
    wait: yes
    group_id: "{{ ec2_security_group }}"
    instance_tags:
      Name: "{{ec2_tag_name}}"
      foo: bar
    exact_count: "{{ ec2_count }}"
    count_tag: foo
    vpc_subnet_id: "{{ ec2_subnet_id }}"
    assign_public_ip: yes
    volumes:
      - device_name: /dev/xvda
        volume_type: gp2
        volume_size: "{{ ec2_volume_size }}"
        delete_on_termination: true
  register: ec2_new

- name: Wait for SSH to come up
  delegate_to: "{{ item.public_dns_name }}"
  wait_for_connection:
    delay: 60
    timeout: 320
  with_items: "{{ ec2_new.instances }}"

- name: Gather facts about all the interested EC2 instances
  ec2_instance_facts:
    filters:
      "tag:Name": "{{ec2_tag_name}}"
      "instance-state-name": "running"
  register: ec2_all

- name: Add instances to host group
  add_host:
    hostname: "{{ item.public_ip_address }}"
    groupname: launched_ec2
  with_items: "{{ ec2_all.instances }}"
