---
- name: Ensure required software is present
  yum:
    name: "{{ item }}"
    enablerepo: epel
  with_items:
    - git
    - nodejs
    - npm

- name: Update environment variables
  lineinfile:
    path: /www/.env
    line: "MACHINE_IP={{ inventory_hostname }}"
    state: present
    create: yes

- name: Ensure that our codebase is up-to-date
  git:
    repo: https://github.com/alcappello/cts-ansible-web
    dest: /www
    force: yes

- name: Install dependencies
  npm:
    path: /www

- name: Install forever globally
  npm:
    name: forever
    global: yes

- name: Ensure that node starts at boot
  become: yes
  cron:
    name: "NodeJS"
    special_time: reboot
    job: "forever start /www/bin/www"
  notify: reboot
